### ISSUE TITLE
vector<LiveShaderPanel*> should be juce::OwnedArray<LiveShaderPanel>

### ISSUE THREAD

**Issue by matkatmusic** [ianacaburian/LiveShaderPalette#1]
https://github.com/ianacaburian/LiveShaderPalette/blob/36ced467a27bf122d3e9b5ed6dc3f96c221a65bf/Source/MainComponent.h#L58

the destructor of your main component never iterates through this vector and deletes each element, so every instance leaks when the app is closed.   You should replace this container with either `std::vector< std::unique_ptr<LiveShaderPanel> >` or `juce::OwnedArray<LiveShaderPanel>` since you're not manually deleting each `LiveShaderPanel` you add here: 
```
void MainComponent::add_panels(const int initial_num_panels, const int num_panels_to_add)
{
    const auto num_fragments = static_cast<int>(fragment_files.size());
    for (int i = initial_num_panels; i != initial_num_panels + num_panels_to_add; ++i) {
        auto* new_panel = panels.emplace_back(new LiveShaderPanel{ *this, i });
```

for this call: 
```
            for (int i = initial_num_panels; --i >= new_num_panels;) {
                removeOpenGLRendererComponent(*panels.erase(panels.begin() + i));
            }
```
As per: https://en.cppreference.com/w/cpp/container/vector/erase, 
```
Iterator following the last removed element. If the iterator pos refers to the last element, the end() iterator is returned.
```
so, and I might be wrong, it seems like your very first LiveShaderPanel is never deleted.

**Comment by ianacaburian** [comment]
The panels are already owned by OpenGLParentComponent in the container std::vector<std::unique_ptr<OpenGLRendererComponent>> children; located in the OpenGLComponent.h line 323. The problem with MainComponent owning the the panels is that its destructor gets called before OpenGLParentComponent and thus destroys OpenGL objects before the context starts its shutdown process, causing bad access errors upon app closing. The LiveShaderPanel raw pointers follow a similar idiom that JUCE's Component system uses, where the Component class holds raw pointers to children and it's up to some other class (in JUCE's case, a derived class) to manage children lifetime. Correct me if I'm wrong and many thanks for your input

**Comment by matkatmusic** [comment]
Ah, i see.  

Perhaps MainComponent could inherit from OpenGLParentComponent instead or some other re-organization of code so it's more obvious where ownership is happening.  You're `new`ing in one class, and ownership is happening in a different class.   That could confuse a lot of people looking at the project.

**Comment by ianacaburian** [comment]
Very true, the only (good) reason I am not flattening the inheritance hierarchy is because there is some small part of me that wants to extend this app to include a scrollable viewport system and so would require a distinction between a parent and top level component. As it stands this confusion is technically unnecessary yes.
